package leafsync

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"platform/internal/leafsync/pbclient"
)

// Bootstrap authenticates to PocketBase as the leaf node and writes the local
// NATS leaf server config (nats-leaf.conf) plus its credentials file, so the
// edge operator can start a stock nats-server with no other inputs.
func Bootstrap(ctx context.Context, cfg *Config) error {
	if cfg.HubLeafURL == "" {
		return fmt.Errorf("nats.hub_leaf_url is required for `config` (the leaf remote has nowhere to dial)")
	}

	pb := pbclient.New(cfg.PocketBaseURL)
	leaf, err := pb.AuthWithPassword(ctx, "leaf_nodes", cfg.PocketBaseEmail, cfg.PocketBasePassword)
	if err != nil {
		return fmt.Errorf("authenticate to PocketBase: %w", err)
	}

	domain, _ := leaf["domain"].(string)
	if domain == "" {
		return fmt.Errorf("leaf node has no domain configured")
	}
	natsUserID, _ := leaf["nats_user"].(string)
	if natsUserID == "" {
		return fmt.Errorf("leaf node has no nats_user assigned yet (provisioning may have failed)")
	}

	// The leaf node's own NATS user → creds + account id.
	natsUser, err := pb.GetOne(ctx, "nats_users", natsUserID)
	if err != nil {
		return fmt.Errorf("fetch nats_user: %w", err)
	}
	creds, _ := natsUser["creds_file"].(string)
	accountID, _ := natsUser["account_id"].(string)
	if creds == "" {
		return fmt.Errorf("nats_user has no creds_file (provisioning incomplete)")
	}
	if accountID == "" {
		return fmt.Errorf("nats_user has no account_id")
	}

	// The org account → account JWT + public key (for resolver_preload).
	account, err := pb.GetOne(ctx, "nats_accounts", accountID)
	if err != nil {
		return fmt.Errorf("fetch nats_account: %w", err)
	}
	accountJWT, _ := account["jwt"].(string)
	accountPub, _ := account["public_key"].(string)
	if accountJWT == "" || accountPub == "" {
		return fmt.Errorf("nats_account missing jwt/public_key")
	}

	// Operator JWT via the dedicated, leaf-node-authenticated route.
	opBytes, err := pb.GetRaw(ctx, "/api/leaf/operator-jwt")
	if err != nil {
		return fmt.Errorf("fetch operator jwt: %w", err)
	}
	var opResp struct {
		OperatorJWT string `json:"operator_jwt"`
	}
	if err := json.Unmarshal(opBytes, &opResp); err != nil {
		return fmt.Errorf("parse operator jwt: %w", err)
	}
	if opResp.OperatorJWT == "" {
		return fmt.Errorf("operator jwt response was empty")
	}

	if err := os.MkdirAll(cfg.OutputDir, 0o755); err != nil {
		return err
	}

	credsName := filepath.Base(cfg.CredsFile)
	credsPath := filepath.Join(cfg.OutputDir, credsName)
	if err := os.WriteFile(credsPath, []byte(creds), 0o600); err != nil {
		return fmt.Errorf("write creds: %w", err)
	}

	conf := buildLeafConf(leafConfParams{
		OperatorJWT: opResp.OperatorJWT,
		AccountPub:  accountPub,
		AccountJWT:  accountJWT,
		Domain:      domain,
		HubLeafURL:  cfg.HubLeafURL,
		CredsName:   credsName,
	})
	confPath := filepath.Join(cfg.OutputDir, "nats-leaf.conf")
	if err := os.WriteFile(confPath, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("write nats-leaf.conf: %w", err)
	}

	fmt.Printf("✅ Wrote %s\n✅ Wrote %s\n", confPath, credsPath)
	fmt.Printf("\nNext: start the leaf with\n  nats-server -c %s\nthen run\n  leaf-sync run\n", confPath)
	return nil
}

type leafConfParams struct {
	OperatorJWT string
	AccountPub  string
	AccountJWT  string
	Domain      string
	HubLeafURL  string
	CredsName   string
}

func buildLeafConf(p leafConfParams) string {
	var b strings.Builder
	b.WriteString("# Generated by leaf-sync `config`. Do not edit by hand.\n")
	b.WriteString("# Regenerate with `leaf-sync config` if the account JWT rotates.\n\n")
	fmt.Fprintf(&b, "server_name: %q\n\n", p.Domain)
	fmt.Fprintf(&b, "jetstream {\n  domain: %q\n  store_dir: \"./jetstream\"\n}\n\n", p.Domain)
	fmt.Fprintf(&b, "operator: %q\n\n", p.OperatorJWT)
	b.WriteString("resolver: MEMORY\n")
	fmt.Fprintf(&b, "resolver_preload: {\n  %s: %q\n}\n\n", p.AccountPub, p.AccountJWT)
	fmt.Fprintf(&b, "leafnodes {\n  remotes: [\n    { url: %q, credentials: %q }\n  ]\n}\n\n", p.HubLeafURL, p.CredsName)
	b.WriteString("# Local monitoring only (no $SYS account); keep bound to localhost.\n")
	b.WriteString("http: \"127.0.0.1:8222\"\n")
	return b.String()
}
